enum AppAction {
  SIGN_IN,
  GET_ARTISTS,
  GET_NOW_PLAYING,
  GET_POPULAR,
  GET_TOP_RATED,
  GET_UPCOMING,
  GET_MOVIE_DETAILS,
  GET_TV_DETAILS,
  GET_TV_TOPRATED,
  GET_TV_POPULAR,
  GET_TV_AIRING,
  GET_TV_ONTHEAIR,
  SEARCH_BY_QUERY
}
